app1/urls.py
from django.urls import path
from app1.views import *

app_name='sree'

urlpatterns=[
    path('lohi/',lohi,name='lohi'),
]

project17/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
from app2.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('lohith/',lohith,name='lohith'),

]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def lohi(request):
    return render(request,'lohi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def lohith(request):
    return render(request,'lohith.html')

templates/lohi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to specific urls page</h1>
        <h1>this page belongs to app1</h1>
        <a href="{% url 'lohith' %}">navigate to genaric urls</a>
    </center>
</body>
</html>

templates/lohith.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to genaric url page</h1>
        <h1>this page belongs to app2</h1>
        <a href="{% url 'sree:lohi' %}">go to specific url</a>
    </center>
</body>
</html>